### ISSUE TITLE
run `cargo test` failed

### ISSUE THREAD

**Issue by zjingwang** [chain/ristretto-bulletproofs#366]
hi, there. i am learning how to use this projects and had this problem:
`
Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.6.1/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown
`

**Comment by ripa1995** [comment]
Your issue lacks a bit of information and also seems to be more an issue related to `rayon` rather than `bulletproofs`, but I'll try to help.

It looks like you are trying to use `bulletproofs` with `rayon` in your custom project, which version of Rustc are you using (`rayon 1.6.1` requires rustc version 1.56+)? Try to run `rustup update`.

**Comment by zjingwang** [comment]
thanks for your help, sir, i'll try to update.

**Comment by 19231224lhr** [comment]
> thanks for your help, sir, i'll try to update.

Dear friends, do you solve this problem?
![image](https://user-images.githubusercontent.com/70199004/233965807-1f91a5bc-2d0a-4565-a630-4d19b7665e34.png)

**Comment by ripa1995** [comment]
> > thanks for your help, sir, i'll try to update.
> 
> Dear friends, do you solve this problem? ![image](https://user-images.githubusercontent.com/70199004/233965807-1f91a5bc-2d0a-4565-a630-4d19b7665e34.png)

Hey,
the issue seems to be related Rust version described in the toolchain and supported by the bulletproofs main branch.
`syn 2.0.15` requires version 1.56.
There are some PRs open / forks that fix such issues ([one ](https://github.com/dalek-cryptography/bulletproofs/pull/364)from our team actually).

**Comment by 19231224lhr** [comment]
> > > thanks for your help, sir, i'll try to update.
> > 
> > 
> > Dear friends, do you solve this problem? ![image](https://user-images.githubusercontent.com/70199004/233965807-1f91a5bc-2d0a-4565-a630-4d19b7665e34.png)
> 
> Hey, the issue seems to be related Rust version described in the toolchain and supported by the bulletproofs main branch. `syn 2.0.15` requires version 1.56. There are some PRs open / forks that fix such issues ([one ](https://github.com/dalek-cryptography/bulletproofs/pull/364)from our team actually).

very thanks! I used your method and finally :
![image](https://user-images.githubusercontent.com/70199004/234162891-7af15437-3ce5-441f-9159-453a555aa279.png)

is this successfully passing the `cargo test`?

**Comment by ripa1995** [comment]
> > > > thanks for your help, sir, i'll try to update.
> > > 
> > > 
> > > Dear friends, do you solve this problem? ![image](https://user-images.githubusercontent.com/70199004/233965807-1f91a5bc-2d0a-4565-a630-4d19b7665e34.png)
> > 
> > 
> > Hey, the issue seems to be related Rust version described in the toolchain and supported by the bulletproofs main branch. `syn 2.0.15` requires version 1.56. There are some PRs open / forks that fix such issues ([one ](https://github.com/dalek-cryptography/bulletproofs/pull/364)from our team actually).
> 
> very thanks! I used your method and finally : ![image](https://user-images.githubusercontent.com/70199004/234162891-7af15437-3ce5-441f-9159-453a555aa279.png)
> 
> is this successfully passing the `cargo test`?

Yes it should be.
