### ISSUE TITLE
Rangeproofs should be typed by their ranges

### ISSUE THREAD

**Issue by hdevalence** [chain/ristretto-bulletproofs#44]
Having separate types for `RangeProof64`, `RangeProof32`, etc. means we can know how big the vectors are, domain separate, ensure that range bitsizes are powers of 2, etc.

**Comment by hdevalence** [comment]
The aggregation is a good point. If we unify the aggregated / single range proof code, then both `n` (bitsize) and `m` are parameters. Both of these can be fed into the transcript, and checked dynamically. So in the end I'm not sure that it's really important to have static typing for `n`.

WDYT?

**Comment by oleganza** [comment]
Yeah, maybe not. My biggest preference is to have unified proof format for verification, so feeding `n,m` into transcript even for `64,1` is a good idea.

Lets get back to this idea once Rust gets const generics ([RFC2000](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md)) ?

**Comment by hdevalence** [comment]
Closing this since we decided to have a unified proof format.
