### ISSUE TITLE
Align aggregated range proofs with single range proofs

### ISSUE THREAD

**Issue by hdevalence** [chain/ristretto-bulletproofs#75]
Right now we have both a `RangeProof` struct and an `AggregatedProof` struct, and more generally we have two seperate implementations of both proving and verifying.

This is a tracking issue for the task of de-duplicating the proof structs and figuring out to what extent it makes sense to do so for the implementation.

**Comment by cathieyun** [comment]
Might make sense to keep the single-value range proof as an unaggregated prover (depending on performance differences)?

Things that would be nice to do before de-duplicating:
- [ ] figure out why the single-party aggregated proof is performing worse than the single-value non-aggregated proof
- [ ] decide on API for the final de-duplicated proof (multi-party case, single-party case)

**Comment by hdevalence** [comment]
On the first point, we should check the performance again after merging #76.

On the second point, with the changes in #76, specifically https://github.com/chain/ristretto-bulletproofs/pull/76/files#diff-c4c4cfaf4c3d4825013213e00bf76be3R129 , the final proof data is the same, except that the inner-product proof is bigger (due to the longer vectors). So the difference between verification of proofs created by the single-value and aggregated code should only be whether a single value commitment or multiple value commitments are passed in, right?

**Comment by cathieyun** [comment]
That makes sense - #76 takes care of both of those items.
