### ISSUE TITLE
Tune benchmark sample sizes for aggregated proof benchmarks

### ISSUE THREAD

**Issue by hdevalence** [chain/ristretto-bulletproofs#82]
The `criterion` config used for all benchmarks is the default one. For things that are expensive (e.g., aggregated proving), this can take a long time:

```
Benchmarking Aggregated 32-bit rangeproof creation/16: Collecting 100 samples in estimated 685.74 s (5050 iterations)
```

Maybe there's a way to turn this down.

**Comment by oleganza** [comment]
I've been tweaking this for my experiments with Pippenger. E.g. here: https://github.com/dalek-cryptography/curve25519-dalek/pull/129/commits/b74b691faeff55226b54ca54efebf67cff1be498#diff-82ae3bb6671596b8982429751ee2b82fL235

**Comment by hdevalence** [comment]
The 32-proof benchmark is even worse, taking 23 minutes.

**Comment by hdevalence** [comment]
This may have been fixed already in https://github.com/chain/ristretto-bulletproofs/commit/4ed2c34721291bb9fd270fce1eabe89d43c4f429 , closing for now.
